version: '3'

services:
  sitl1:
    image: sitl:latest
    container_name: sitl1
    ports:
      - "4201:5760"
      - "4301:5763"
    command: >
      /bin/bash -c "/ardupilot/Tools/autotest/sim_vehicle.py --vehicle ${VEHICLE} -f ${FILE1} -I${INSTANCE} --custom-location=${LAT},${LON},${ALT},${DIR} -w --frame ${MODEL} --no-rebuild --no-mavproxy --speedup ${SPEEDUP} --add-param-file=/ardupilot/Tools/autotest/default_params/gazebo-drone1.parm"
  sitl2:
    image: sitl:latest
    container_name: sitl2
    ports:
      - "4202:5760"
      - "4302:5763"
    command: >
      /bin/bash -c "/ardupilot/Tools/autotest/sim_vehicle.py --vehicle ${VEHICLE} -f ${FILE2} -I${INSTANCE} --custom-location=${LAT},${LON},${ALT},${DIR} -w --frame ${MODEL} --no-rebuild --no-mavproxy --speedup ${SPEEDUP} --add-param-file=/ardupilot/Tools/autotest/default_params/gazebo-drone2.parm"